name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup
      id: setup
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Setup
        setup-command: ''
        command: bash ./submission/setup.sh
        timeout: 10
    - name: What is the hash of block 654,321?
      id: what-is-the-hash-of-block-654-321
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: What is the hash of block 654,321?
        setup-command: ''
        command: bash ./submission/001.sh
        input: ''
        expected-output: '000000000000000000058452bbe379ad4364fe8fda68c45e299979b492858095'
        comparison-method: exact
        timeout: 10
        max-score: 1
    - name: Verify the signature by this address over this message...
      id: verify-the-signature-by-this-address-over-this-message
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Verify the signature by this address over this message...
        setup-command: ''
        command: bash ./submission/002.sh
        input: ''
        expected-output: 'false'
        comparison-method: exact
        timeout: 10
        max-score: 1
    - name: How many new outputs were created by block 123,456?
      id: how-many-new-outputs-were-created-by-block-123-456
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: How many new outputs were created by block 123,456?
        setup-command: ''
        command: bash ./submission/003.sh
        input: ''
        expected-output: '24'
        comparison-method: exact
        timeout: 10
        max-score: 1
    - name: Using descriptors, compute the 100th taproot address derived from this
        extended public key...
      id: using-descriptors-compute-the-100th-taproot-address-derived-from-this-extended-public-key
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Using descriptors, compute the 100th taproot address derived from
          this extended public key...
        setup-command: ''
        command: bash ./submission/004.sh
        input: ''
        expected-output: bc1p3yrtpvv6czx63h2sxwmeep8q98h94w4288fc4cvrkqephalydfgszgacf9
        comparison-method: exact
        timeout: 10
        max-score: 1
    - name: Create a 1-of-4 P2SH multisig address from the public keys in the four
        inputs of this tx...
      id: create-a-1-of-4-p2sh-multisig-address-from-the-public-keys-in-the-four-inputs-of-this-tx
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Create a 1-of-4 P2SH multisig address from the public keys in the
          four inputs of this tx...
        setup-command: ''
        command: bash ./submission/005.sh
        input: ''
        expected-output: 3GyWg1CCD3RDpbwCbuk9TTRQptkRfczDz8
        comparison-method: exact
        timeout: 10
        max-score: 1
    - name: Which tx in block 257,343 spends the coinbase output of block 256,128?
      id: which-tx-in-block-257-343-spends-the-coinbase-output-of-block-256-128
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Which tx in block 257,343 spends the coinbase output of block 256,128?
        setup-command: ''
        command: bash ./submission/006.sh
        input: ''
        expected-output: c54714cb1373c2e3725261fe201f267280e21350bdf2df505da8483a6a4805fc
        comparison-method: exact
        timeout: 10
        max-score: 1
    - name: Only one single output remains unspent from block 123,321. What address
        was it sent to?
      id: only-one-single-output-remains-unspent-from-block-123-321-what-address-was-it-sent-to
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Only one single output remains unspent from block 123,321. What
          address was it sent to?
        setup-command: ''
        command: bash ./submission/007.sh
        input: ''
        expected-output: 1FPDNNmgwEnKuF7GQzSqUcVQdzSRhz4pgX
        comparison-method: exact
        timeout: 10
        max-score: 1
    - name: Which public key signed input 0 in this tx...
      id: which-public-key-signed-input-0-in-this-tx
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Which public key signed input 0 in this tx...
        setup-command: ''
        command: bash ./submission/008.sh
        input: ''
        expected-output: 025d524ac7ec6501d018d322334f142c7c11aa24b9cffec03161eca35a1e32a71f
        comparison-method: exact
        timeout: 10
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        SETUP_RESULTS: "${{steps.setup.outputs.result}}"
        WHAT-IS-THE-HASH-OF-BLOCK-654-321_RESULTS: "${{steps.what-is-the-hash-of-block-654-321.outputs.result}}"
        VERIFY-THE-SIGNATURE-BY-THIS-ADDRESS-OVER-THIS-MESSAGE_RESULTS: "${{steps.verify-the-signature-by-this-address-over-this-message.outputs.result}}"
        HOW-MANY-NEW-OUTPUTS-WERE-CREATED-BY-BLOCK-123-456_RESULTS: "${{steps.how-many-new-outputs-were-created-by-block-123-456.outputs.result}}"
        USING-DESCRIPTORS-COMPUTE-THE-100TH-TAPROOT-ADDRESS-DERIVED-FROM-THIS-EXTENDED-PUBLIC-KEY_RESULTS: "${{steps.using-descriptors-compute-the-100th-taproot-address-derived-from-this-extended-public-key.outputs.result}}"
        CREATE-A-1-OF-4-P2SH-MULTISIG-ADDRESS-FROM-THE-PUBLIC-KEYS-IN-THE-FOUR-INPUTS-OF-THIS-TX_RESULTS: "${{steps.create-a-1-of-4-p2sh-multisig-address-from-the-public-keys-in-the-four-inputs-of-this-tx.outputs.result}}"
        WHICH-TX-IN-BLOCK-257-343-SPENDS-THE-COINBASE-OUTPUT-OF-BLOCK-256-128_RESULTS: "${{steps.which-tx-in-block-257-343-spends-the-coinbase-output-of-block-256-128.outputs.result}}"
        ONLY-ONE-SINGLE-OUTPUT-REMAINS-UNSPENT-FROM-BLOCK-123-321-WHAT-ADDRESS-WAS-IT-SENT-TO_RESULTS: "${{steps.only-one-single-output-remains-unspent-from-block-123-321-what-address-was-it-sent-to.outputs.result}}"
        WHICH-PUBLIC-KEY-SIGNED-INPUT-0-IN-THIS-TX_RESULTS: "${{steps.which-public-key-signed-input-0-in-this-tx.outputs.result}}"
      with:
        runners: setup,what-is-the-hash-of-block-654-321,verify-the-signature-by-this-address-over-this-message,how-many-new-outputs-were-created-by-block-123-456,using-descriptors-compute-the-100th-taproot-address-derived-from-this-extended-public-key,create-a-1-of-4-p2sh-multisig-address-from-the-public-keys-in-the-four-inputs-of-this-tx,which-tx-in-block-257-343-spends-the-coinbase-output-of-block-256-128,only-one-single-output-remains-unspent-from-block-123-321-what-address-was-it-sent-to,which-public-key-signed-input-0-in-this-tx
